# Generated by Django 2.1.1 on 2018-09-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssido_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingpong', models.CharField(default='unknown', max_length=50)),
                ('basketball', models.IntegerField(default='unknown', max_length=50)),
                ('baseball', models.CharField(default='unknown', max_length=50)),
            ],
        ),
    ]
